
version: "3.7"
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
     
    
  backend:
    build: ./backend
    ports:
    - 4000:4000
    environment:
      DB_URL: mongodb://db/Csteam
    volumes:
      - ./backend:/app

volumes:
  Csteam:
  data:
